version: 30

model:
  provider: openai_compatible
  name: minimaxai/minimax-m2.7
  base_url: https://integrate.api.nvidia.com/v1
  api_key: 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
  temperature: 1.0
  top_p: 0.95
  max_tokens: 8192

gateway:
  autostart: true
  platforms:
    telegram:
      enabled: true
      bot_token: "8917655310:AAF-vvKAu-SXb8Kq7fBGT1Z3HKHRiX5k4P8"
      allowed_users:
        - "8925763918"
